name: Build & Push
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to quay
        env:
          CONTAINER_USER: ${{ secrets.QUAY_USER }}
          CONTAINER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          CONTAINER_REGISTRY: quay.io
        run:
          docker login -u $CONTAINER_USER -p $CONTAINER_PASSWORD $CONTAINER_REGISTRY

      - name: Build images
        run: |
          make java_build
          make docker_build

      - name: Tag & Push
        env:
          USER: tealc
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          make docker_push